name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: check out source code
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: install dependency and build 
    - run: npm install
